# Welcome

It is highly recommended that you have a look at parts one, two and three of this series
Lets begin

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

## Stacking

This is a very powerful feature of numpy. To adjoin matrices under or adjacent to each other, these two commands can be invoked

### Vertical Stacking

Pretty self explanatory  

In [4]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Horizontal Stacking

Same but horizontally

In [5]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Splitting

The opposite of stacking. It basically splits it into the number of times required as passed as parameter



In [7]:
x = np.hsplit(a, 2)

In [8]:
x[0]

array([[1],
       [3]])

In [9]:
x[1]

array([[2],
       [4]])

In [12]:
x = np.vsplit(a, 2)

In [13]:
x[0]

array([[1, 2]])

In [14]:
x[1]

array([[3, 4]])

# Thank You 

Hope you had a good time going through this notebook. You will now be equiped with all essential numpy functions.

A few optional exercises will be on **boolean indexing** and **nditer** which I might include later if requested. They are small but very useful concepts. You can perform those operations with your current numpy and basic python knoledge but these are one liner substitutes. Thank you 